//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPArbitrageMissForYou
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbitrageClients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArbitrageClients()
        {
            this.AdminoWorld = new HashSet<AdminoWorld>();
            this.History = new HashSet<History>();
            this.P2PHelper = new HashSet<P2PHelper>();
            this.SpotFinancialHelper = new HashSet<SpotFinancialHelper>();
        }
    
        public int Id { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
        public string API1Huobi { get; set; }
        public string API1HuobiSecretKey { get; set; }
        public string API2Binance { get; set; }
        public string API2BinanceSecretKey { get; set; }
        public string API3Uniswap { get; set; }
        public string API3UniswapSecretKey { get; set; }
        public string API4Kraken { get; set; }
        public string API4KrakenSecretKey { get; set; }
        public string API5Pancakeswap { get; set; }
        public string API5PancakeswapSecretKey { get; set; }
        public string Passphrase { get; set; }
        public string Passphrase2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminoWorld> AdminoWorld { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P2PHelper> P2PHelper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpotFinancialHelper> SpotFinancialHelper { get; set; }
    }
}
