//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPArbitrageMissForYou
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int Id_clients { get; set; }
        public string exchanges { get; set; }
        public Nullable<decimal> profit { get; set; }
        public Nullable<decimal> sold { get; set; }
        public Nullable<decimal> bought { get; set; }
        public Nullable<System.DateTime> timehistory { get; set; }
        public Nullable<decimal> totalprofit { get; set; }
    
        public virtual ArbitrageClients ArbitrageClients { get; set; }
    }
}
