//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPArbitrageMissForYou
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotFinancialHelper
    {
        public int Id { get; set; }
        public int Id_clients { get; set; }
        public string cryptopair { get; set; }
        public string exchanges { get; set; }
        public Nullable<int> investments { get; set; }
        public Nullable<decimal> profitofthemash { get; set; }
        public Nullable<System.DateTime> timehistory { get; set; }
    
        public virtual ArbitrageClients ArbitrageClients { get; set; }
    }
}
